#  location: "./custom-snapshot.yaml"
resolver: lts-9.1

flags:
  ether:
    disable-tup-instances: true

extra-package-dbs: []

packages:
- .

# input-output-hk dependencies
- location:
    git: https://github.com/input-output-hk/cardano-sl
    commit: c489f3ecd12e2b23476640ddd77057e535953b31
  subdirs:
    - networking
    - binary
    - block
    - client
    - util
    - delegation
    - generator
    - lib
    - lrc
    - ssc
    - txp
    - update
    - core
    - crypto
    - infra
    - db
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/cardano-report-server.git
    commit: 7b28613c9c3535193991712ff5a4a36a9f165570
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/plutus-prototype
    commit: d4aa461fc69fc6957aab46b41a670c2144aefb77
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/cardano-crypto
    commit: 1cde8e3a8d9093bbf571085920045c05edb3eaa4
  extra-dep: true

# serokell dependencies
- location:
    git: https://github.com/serokell/time-units.git
    commit: 6c3747c1ac794f952de996dd7ba8a2f6d63bf132
  extra-dep: true
- location:
    git: https://github.com/serokell/kademlia.git
    commit: 7120bb4d28e708acd52dfd61d3dca7914fac7d7f
  extra-dep: true
- location:
    git: https://github.com/serokell/acid-state.git
    commit: 95fce1dbada62020a0b2d6aa2dd7e88eadd7214b
  extra-dep: true
- location:
    git: https://github.com/serokell/time-warp-nt.git
    commit: 74acf3c98ec402490e4ae086a60227560cde166d
  extra-dep: true
- location:
    git: https://github.com/serokell/network-transport-tcp
    commit: 24dd213cef81d383083feb7f5d9ce4b8a6be8168
  extra-dep: true
- location:
    git: https://github.com/serokell/network-transport
    commit: 018a50b9042c2115c3ec9c9fd5ca5f28737dd29c
  extra-dep: true
- location:
    git: https://github.com/avieth/network-transport-inmemory
    commit: 5d8ff2b07b9df35cf61329a3d975e2c8cf95c12a
  extra-dep: true
# This is required due to undefined symbol in Hackage variant.
- location:
    git: https://github.com/serokell/swagger2
    commit: 6693ff91be2f0b015c2ab043292587c1cc9449cf
  extra-dep: true

# well-typed dependencies
- location:
    git: https://github.com/well-typed/cborg
    commit: c7db82bfd93923f5b08ed51a4cd53e30bd445924
  subdirs:
    - cborg
  extra-dep: true
- location:
    git: https://github.com/well-typed/canonical-json.git
    commit: 2d261bb971bada1893753b503452d9e6e217bc4a
  extra-dep: true

# other dependencies
- location:
    git: https://github.com/kazu-yamamoto/dns.git
    commit: b106470f0a93672af22cbc7ed6564b53c0f249ed
  extra-dep: true

- location:
    git: https://github.com/thoughtpolice/hs-ed25519
    commit: da4247b5b3420120e20451e6a252e2a2ca15b43c
  extra-dep: true

extra-deps:
#  - acid-state-0.14.1
  - base58-bytestring-0.1.0
  - concurrent-extra-0.7.0.10
#  - cryptonite-0.23
  - ekg-core-0.1.1.3
  - entropy-0.3.7             # https://github.com/commercialhaskell/stack/issues/3151
  - fmt-0.5.0.0
  - foldl-1.3.5
  - generic-arbitrary-0.1.0
  - happy-1.19.5              # https://github.com/commercialhaskell/stack/issues/3151
  - ixset-typed-0.3.1.1
  - loc-0.1.3.1
  - log-warper-1.8.0
  - MonadRandom-0.5.1
  - mmorph-1.0.9
  - pvss-0.2.0
  - rocksdb-haskell-1.0.0
  - systemd-1.1.2
  - ether-0.5.1.0
  - hashable-1.2.6.1
  - random-1.1
  - safecopy-0.9.3.2
  - serokell-util-0.5.2
  - servant-0.12
  - servant-server-0.12
  - servant-multipart-0.11
  - servant-docs-0.11.1             # needed for servant-0.12
  - servant-generic-0.1.0.1
  - servant-swagger-1.1.4           # needed for servant-0.12
  - servant-swagger-ui-0.2.4.3.4.0  # needed for servant-0.12
  - syb-with-class-0.6.1.8          # needed for ixset-1.0.7
  - universum-0.9.0
  - vector-0.12.0.1
  - vector-builder-0.3.4.1

apply-ghc-options: everything

nix:
  pure: true
  shell-file: shell.nix
